jobs:
- job: BUILDVS2017
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: |
      echo "hello from vmImage vs2017-win2016"
      echo "compile webnoauth.csproj using VS2017"

  - task: NugetRestore@2
    displayName: Restore nuget WebFormsNoAuth.csproj
    inputs: 
        command: restore
        solution: $(Build.SourcesDirectory)\aspnetfx\ASPNET.WebForms.v4.7.2\ASPNET.WebForms.v4.7.2.sln
    
  - task: MSBuild@1
    displayName: Build WebFormsNoAuth.csproj
    inputs:
      solution: $(Build.SourcesDirectory)\aspnetfx\ASPNET.WebForms.v4.7.2\ASPNET.WebForms.v4.7.2.sln
      msbuildLocationMethod: version
      msbuildVersion: '15.0'
      configuration: "Release"
      msbuildArguments: /nologo /p:DeployOnBuild=true /p:PublishProfile=FolderProfile2
      clean: 'false'
      maximumCpuCount: 'false'

  - script: |
      echo "copy result to staging"
      xcopy $(Build.SourcesDirectory)\aspnetfx\ASPNET.WebForms.v4.7.2\WebFormsNoAuth\bin\Release\Publish $(Build.ArtifactStagingDirectory) /E

- job: WindowsContainer
  dependsOn: BUILDVS2017
  pool:
    vmImage: 'win1803'
  steps:
  - script: |
      echo "hello from vmImage win1803"
      md buildresult
      echo "copy buildresult into build folder"
      xcopy $(Build.ArtifactStagingDirectory) buildresult /E
      echo "begin build docker image"